version = 1
SPDX-PackageName = "laelaps"
SPDX-PackageSupplier = "Jan Maarten van Doorn <laelaps@vandoorn.cloud>"
SPDX-PackageDownloadLocation = "https://github.com/JanMaartenvanDoorn/Laelaps"
annotations = []
