# SPDX-FileCopyrightText: 2024 Jan Maarten van Doorn <laelaps@vandoorn.cloud>
#
# SPDX-License-Identifier: MPL-2.0

version = 1
SPDX-PackageName = "laelaps"
SPDX-PackageSupplier = "Jan Maarten van Doorn <laelaps@vandoorn.cloud>"
SPDX-PackageDownloadLocation = "https://github.com/JanMaartenvanDoorn/Laelaps"
annotations = []
