# SPDX-FileCopyrightText: 2023 Jan Maarten van Doorn <laelaps@vandoorn.cloud>
#
# SPDX-License-Identifier: MPL-2.0
name: Python Build and Test

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install .
        pip install .[test]
    - name: isort
      run: isort . --check-only
    - name: black
      run: black --check .
    - name: bandit
      run: bandit -r ./laelaps
    - name: pflake8
      run: pflake8 .
    - name: mypy
      run: mypy laelaps
    - name: pydocstyle
      run: pydocstyle laelaps
    - name: pylint
      run: pylint laelaps
    - name: pytest
      run: pytest tests
